version: "3.7"

services:
  parislapresmidi-tracking-parcels:
    image: gaspardcothiasfaure/parislapresmidi-tracking-parcels:0.1
    container_name: parislapresmidi-tracking-parcels
    restart: always
    env_file: .env
    volumes:
      - "/home/debian/parislapresmidi-tracking-parcels/output:/app/output"
      - "/home/debian/parislapresmidi-tracking-parcels/GOOGLE_DRIVE_API_USER_TOKEN_FILE.json:/app/source-code/GOOGLE_DRIVE_API_USER_TOKEN_FILE.json"