name: build and publish to Docker Hub on push to main

on:
  push:
    branches:
      - main

jobs:
  deploy-app:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: gaspardcothiasfaure/anniv.lgna.fr:0.2

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Copy docker-compose.yml into VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          source: "docker-compose.yml"
          overwrite: true
          target: "/home/debian/lgna-sandbox/anniv.lgna.fr"

      - name: Pull latest Docker image and launch docker-compose.yml
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            docker pull gaspardcothiasfaure/anniv.lgna.fr:0.2
            docker-compose -f /home/debian/lgna-sandbox/anniv.lgna.fr/docker-compose.yml --env-file /home/debian/lgna-sandbox/anniv.lgna.fr/.env up -d
